name: game-collector
version: 1.0.10
summary: 收集金幣，看你最多拿幾個金幣!
description: |
 這款遊戲玩家可以用觸控操縱一隻不明生物，左、右移動，收集天空隨機掉下來的金幣，會有分數累積，但如果被流星錘砸到，就遊戲結束。分數愈高、難度愈高。
 遊戲結束後，分數若能超過排行榜前10名任一名，則會記錄分數。
 
grade: stable
confinement: strict
base: core20

parts:
  game-collector:
    plugin: dump
    source: snap/local

apps:
   game-collector:
     command: linux.x86_64
     extensions: [gnome-3-38]
     plugs: [network]
